modLoader = "javafml"
loaderVersion = "[46,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "theatricalextralights"
version = "${version}"
displayName = "Theatrical: Extra Lights"
authors = "dumann089, Rushmead, J8-Diablo"
description = '''
Addon for Theatrical — moving heads, LED panels, PARs, water jets, pyro, lasers, and more stage lighting fixtures with DMX / Art-Net support.
'''
#logoFile = ""

[[dependencies.theatricalextralights]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.theatricalextralights]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.theatricalextralights]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.12,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.theatricalextralights]]
modId = "theatrical"
mandatory = true
versionRange = "[1.0.0-alpha.23,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "theatricalextralights-common.mixins.json"
