org.gradle.jvmargs=-Xmx4G

minecraft_version=1.20.1
enabled_platforms=fabric,forge

archives_base_name=TheatricalExtraLights
mod_version=1.4.7-beta
maven_group=com.github.dumann089

architectury_version=9.1.12

fabric_loader_version=0.15.11
fabric_api_version=0.90.4+1.20.1

forge_version=1.20.1-47.2.1

shimmer_version=1.20.1-0.2.4

modmenu_version=7.2.2

neoforge_version=20.2.75-beta

parchment_version=2023.09.03

theatrical_version=1.0.0-alpha.28.120+mc1.20.1

include_shimmer=true
